package agent;

import simulation.Board;

/**
 * This class automatically adds some simple statistics to the solutions
 * generated by subclasses
 * 
 * @author Marjie
 * 
 */
public abstract class AbstractAgent implements Agent {

	@Override
	public final Solution findSolution(Board startState) {
		Board.resetCount();
		long startTime = System.currentTimeMillis();
		Solution s = doFindSolution(startState);
		s.addStatistic("Time (ms)", System.currentTimeMillis() - startTime);
		s.addStatistic("Steps", s.length());
		s.addStatistic("Nodes Visited", Board.getCount());
		return s;
	}

	protected abstract Solution doFindSolution(Board startState);
}
